/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Locale;

/**
 *
 * @author admin
 */
public class MainStaff extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainStaff.class.getName());

    /**
     * Creates new form MainStaff
     */
    public MainStaff() {
        initComponents();
        
        setLocationRelativeTo(null);
        
        String today = getToday();
        pnDate.setText(today);
        
        String timeToday = getTimeToday();
        pnTimeToday.setText(timeToday);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        borderR1 = new Views.BorderR();
        pnName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pnDate = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnTimeToday = new javax.swing.JLabel();
        btnCheckin = new javax.swing.JButton();
        btnCheckin1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        scrollTimesheet = new javax.swing.JScrollPane();
        dataTimeSheet = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        btnEditStaff = new javax.swing.JButton();
        btnExitStaff = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));

        borderR1.setBackground(new java.awt.Color(255, 255, 255));

        pnName.setFont(new java.awt.Font("Segoe UI Semibold", 2, 18)); // NOI18N
        pnName.setText("Xin chào, Tên nhân viên");

        pnDate.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        pnDate.setText("Ngày: ");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N

        pnTimeToday.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        pnTimeToday.setForeground(new java.awt.Color(255, 153, 153));
        pnTimeToday.setText("Giờ");

        btnCheckin.setBackground(new java.awt.Color(0, 153, 204));
        btnCheckin.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnCheckin.setForeground(new java.awt.Color(255, 255, 255));
        btnCheckin.setText("Check-out");
        btnCheckin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckinActionPerformed(evt);
            }
        });

        btnCheckin1.setBackground(new java.awt.Color(0, 153, 51));
        btnCheckin1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnCheckin1.setForeground(new java.awt.Color(255, 255, 255));
        btnCheckin1.setText("Check-In");
        btnCheckin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckin1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout borderR1Layout = new javax.swing.GroupLayout(borderR1);
        borderR1.setLayout(borderR1Layout);
        borderR1Layout.setHorizontalGroup(
            borderR1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borderR1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(pnName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(31, 31, 31)
                .addComponent(pnDate, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(borderR1Layout.createSequentialGroup()
                .addGroup(borderR1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(borderR1Layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(pnTimeToday))
                    .addGroup(borderR1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(btnCheckin1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(72, 72, 72)
                        .addComponent(btnCheckin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        borderR1Layout.setVerticalGroup(
            borderR1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borderR1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(borderR1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pnName)
                    .addComponent(pnDate)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnTimeToday)
                .addGroup(borderR1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(borderR1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, borderR1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addGroup(borderR1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCheckin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCheckin1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        jLabel1.setText("Chấm Công");

        dataTimeSheet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Ngày", "Giờ vào", "Giờ ra", "Tổng giờ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollTimesheet.setViewportView(dataTimeSheet);

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel4.setText("Lịch sử chấm công");

        btnEditStaff.setBackground(new java.awt.Color(0, 153, 0));
        btnEditStaff.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnEditStaff.setForeground(new java.awt.Color(255, 255, 255));
        btnEditStaff.setText("Chỉnh sửa");
        btnEditStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditStaffActionPerformed(evt);
            }
        });

        btnExitStaff.setBackground(new java.awt.Color(255, 0, 51));
        btnExitStaff.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnExitStaff.setForeground(new java.awt.Color(255, 255, 255));
        btnExitStaff.setText("Thoát");
        btnExitStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitStaffActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(borderR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnEditStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(52, Short.MAX_VALUE)
                    .addComponent(scrollTimesheet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(75, 75, 75)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(btnExitStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(413, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(borderR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 231, Short.MAX_VALUE)
                .addComponent(btnEditStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(261, 261, 261)
                    .addComponent(scrollTimesheet, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(92, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(488, Short.MAX_VALUE)
                    .addComponent(btnExitStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(15, 15, 15)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCheckinActionPerformed

    private void btnCheckin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCheckin1ActionPerformed

    private void btnExitStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitStaffActionPerformed
        Login login = new Login();
        
        login.setLocationRelativeTo(null);
        login.setVisible(true);
                
        this.dispose();
    }//GEN-LAST:event_btnExitStaffActionPerformed

    private void btnEditStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditStaffActionPerformed
        EditAccToMe edit = new EditAccToMe();
        
        edit.setLocationRelativeTo(null);
        edit.setVisible(true);
                
        this.dispose();
    }//GEN-LAST:event_btnEditStaffActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainStaff().setVisible(true));
    }
    
    public String getToday() {
    // 1. Lấy thời gian thực hiện tại
    LocalDateTime now = LocalDateTime.now(); 
    
    // 2. Định dạng lại cho đẹp (Ví dụ: 10/12/2025 15:30:00)
    DateTimeFormatter dtf = DateTimeFormatter.ofPattern("EEE, dd/MM/yyyy", new Locale("vi", "VN"));
    
    // 3. Trả về chuỗi
    return dtf.format(now);
}
    public String getTimeToday() {
    // 1. Lấy thời gian thực hiện tại
    LocalDateTime now = LocalDateTime.now(); 
    
    // 2. Định dạng lại cho đẹp (Ví dụ: 10/12/2025 15:30:00)
    DateTimeFormatter dtf = DateTimeFormatter.ofPattern("HH:mm:ss");
    
    // 3. Trả về chuỗi
    return dtf.format(now);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Views.BorderR borderR1;
    private javax.swing.JButton btnCheckin;
    private javax.swing.JButton btnCheckin1;
    private javax.swing.JButton btnEditStaff;
    private javax.swing.JButton btnExitStaff;
    private javax.swing.JTable dataTimeSheet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel pnDate;
    private javax.swing.JLabel pnName;
    private javax.swing.JLabel pnTimeToday;
    private javax.swing.JScrollPane scrollTimesheet;
    // End of variables declaration//GEN-END:variables
}
