/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

import java.awt.Color;
import java.awt.Component;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class PanelManagerTimesheet extends javax.swing.JPanel {

    /**
     * Creates new form PanelManagerSalary
     */
    public PanelManagerTimesheet() {
        initComponents();
        
        initMockData();
        decorateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainTimesheet = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtSearch = new Views.RoundedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableData = new javax.swing.JTable();
        combStatus = new javax.swing.JComboBox<>();

        MainTimesheet.setBackground(new java.awt.Color(245, 245, 245));
        MainTimesheet.setAlignmentX(0.0F);

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 2, 36)); // NOI18N
        jLabel3.setText("Danh sách chấm công");

        txtSearch.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N

        tableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã NV", "Họ và Tên", "Ngày", "Giờ vào", "Giờ ra", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableData);

        combStatus.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        combStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Đúng giờ", "Đi muộn", "Nghỉ phép" }));

        javax.swing.GroupLayout MainTimesheetLayout = new javax.swing.GroupLayout(MainTimesheet);
        MainTimesheet.setLayout(MainTimesheetLayout);
        MainTimesheetLayout.setHorizontalGroup(
            MainTimesheetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainTimesheetLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(combStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainTimesheetLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(MainTimesheetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainTimesheetLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 846, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainTimesheetLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(241, 241, 241))))
        );
        MainTimesheetLayout.setVerticalGroup(
            MainTimesheetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainTimesheetLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(MainTimesheetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 888, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(MainTimesheet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 581, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(MainTimesheet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void initMockData() {
        // Lấy model của bảng (giả sử tên bảng là tableLuong)
        DefaultTableModel model = (DefaultTableModel) tableData.getModel();
        
        // Xóa sạch dữ liệu cũ
        model.setRowCount(0);

        // Thêm dữ liệu mẫu
        // Cấu trúc: Mã NV, Tên, Ngày, Giờ Vào, Giờ Ra, Trạng Thái
        model.addRow(new Object[]{"NV001", "Nguyễn Văn A", "09/12/2025", "07:55", "17:30", "Đúng giờ"});
        model.addRow(new Object[]{"NV002", "Trần Thị B",   "09/12/2025", "08:05", "17:30", "Đi muộn"});
        model.addRow(new Object[]{"NV003", "Lê Văn C",     "09/12/2025", "07:50", "17:00", "Đúng giờ"});
        model.addRow(new Object[]{"NV004", "Phạm Thị D",   "09/12/2025", "--:--", "--:--", "Nghỉ phép"});
        model.addRow(new Object[]{"NV005", "Hoàng Văn E",  "09/12/2025", "08:30", "17:30", "Đi muộn"});
        model.addRow(new Object[]{"NV001", "Nguyễn Văn A", "10/12/2025", "07:58", "17:35", "Đúng giờ"});
    }
    
    private void decorateTable() {
        tableData.getColumnModel().getColumn(5).setCellRenderer(new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                String status = (String) value;
                
                // Logic tô màu chữ dựa theo trạng thái
                if ("Đi muộn".equals(status)) {
                    setForeground(Color.RED);
                    setFont(getFont().deriveFont(java.awt.Font.BOLD));
                } else if ("Đúng giờ".equals(status)) {
                    setForeground(new Color(0, 150, 0)); // Màu xanh lá
                } else if ("Nghỉ phép".equals(status)) {
                    setForeground(Color.GRAY);
                } else {
                    setForeground(Color.BLACK);
                }
                return c;
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainTimesheet;
    private javax.swing.JComboBox<String> combStatus;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableData;
    private Views.RoundedTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
