/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class PanelManagerStaff extends javax.swing.JPanel {

    /**
     * Creates new form PanelManagerStaff
     */
    public PanelManagerStaff() {
        initComponents();
        
        initTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainManagerStaff = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtSearch = new Views.RoundedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableData = new javax.swing.JTable();
        combbPosition = new javax.swing.JComboBox<>();
        btnEditStaff = new javax.swing.JButton();
        btnAddStaff = new javax.swing.JButton();
        btnEditStaff1 = new javax.swing.JButton();

        MainManagerStaff.setBackground(new java.awt.Color(245, 245, 245));
        MainManagerStaff.setAlignmentX(0.0F);

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 2, 36)); // NOI18N
        jLabel3.setText("Quản Lý Nhân Viên");

        txtSearch.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N

        tableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã NV", "Họ và Tên", "Tài Khoản", "Số Điện Thoại", "Chức Vụ", "Giới Tính"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableData);

        combbPosition.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        combbPosition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Dev", "Nhân Sự", "Marketing" }));

        btnEditStaff.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnEditStaff.setText("Chỉnh Sửa");
        btnEditStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditStaffActionPerformed(evt);
            }
        });

        btnAddStaff.setBackground(new java.awt.Color(0, 102, 204));
        btnAddStaff.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnAddStaff.setForeground(new java.awt.Color(255, 255, 255));
        btnAddStaff.setText("+ Thêm Nhân Viên");
        btnAddStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStaffActionPerformed(evt);
            }
        });

        btnEditStaff1.setBackground(new java.awt.Color(255, 51, 51));
        btnEditStaff1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnEditStaff1.setText("Xóa");

        javax.swing.GroupLayout MainManagerStaffLayout = new javax.swing.GroupLayout(MainManagerStaff);
        MainManagerStaff.setLayout(MainManagerStaffLayout);
        MainManagerStaffLayout.setHorizontalGroup(
            MainManagerStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainManagerStaffLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(combbPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditStaff)
                .addGap(18, 18, 18)
                .addComponent(btnEditStaff1)
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(MainManagerStaffLayout.createSequentialGroup()
                .addGroup(MainManagerStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainManagerStaffLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 846, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainManagerStaffLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddStaff)))
                .addContainerGap())
        );
        MainManagerStaffLayout.setVerticalGroup(
            MainManagerStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainManagerStaffLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainManagerStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btnAddStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MainManagerStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combbPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditStaff1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 888, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(MainManagerStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 581, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(MainManagerStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

        private void initTableData() {
    // 1. Lấy mô hình dữ liệu của bảng hiện tại
    DefaultTableModel model = (DefaultTableModel) tableData.getModel();
    
    // 2. Xóa hết dữ liệu cũ (nếu có)
    model.setRowCount(0);
    
    // 3. Thêm các dòng dữ liệu mẫu (Object[] là mảng chứa dữ liệu từng cột theo thứ tự)
    model.addRow(new Object[]{"NV001", "Nguyễn Văn A", "nguyenvana@email.com", "0901234567", "Kỹ thuật", "Senior Dev", "Hoạt động"});
    model.addRow(new Object[]{"NV002", "Trần Thị B", "tranthib@email.com", "0902345678", "Nhân sự", "HR Manager", "Hoạt động"});
    model.addRow(new Object[]{"NV003", "Lê Văn C", "levanc@email.com", "0903456789", "Kinh doanh", "Sale", "Ngừng hoạt động"});
    model.addRow(new Object[]{"NV001", "Nguyễn Văn A", "nguyenvana@email.com", "0901234567", "Kỹ thuật", "Senior Dev", "Hoạt động"});
    model.addRow(new Object[]{"NV002", "Trần Thị B", "tranthib@email.com", "0902345678", "Nhân sự", "HR Manager", "Hoạt động"});
    model.addRow(new Object[]{"NV003", "Lê Văn C", "levanc@email.com", "0903456789", "Kinh doanh", "Sale", "Ngừng hoạt động"});
    model.addRow(new Object[]{"NV001", "Nguyễn Văn A", "nguyenvana@email.com", "0901234567", "Kỹ thuật", "Senior Dev", "Hoạt động"});
    model.addRow(new Object[]{"NV002", "Trần Thị B", "tranthib@email.com", "0902345678", "Nhân sự", "HR Manager", "Hoạt động"});
    model.addRow(new Object[]{"NV003", "Lê Văn C", "levanc@email.com", "0903456789", "Kinh doanh", "Sale", "Ngừng hoạt động"});
}
    
    private void btnEditStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditStaffActionPerformed
        // TODO add your handling code here:
        EditStaff edit = new EditStaff();
        edit.setTitle("Thêm Nhân Viên Mới");
        edit.setLocationRelativeTo(null);
        edit.setAlwaysOnTop(true);
        edit.setVisible(true);
    }//GEN-LAST:event_btnEditStaffActionPerformed

    private void btnAddStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStaffActionPerformed
        // TODO add your handling code here:
        AddStaff add = new AddStaff();
        add.setTitle("Thêm Nhân Viên Mới");
        add.setLocationRelativeTo(null);
        add.setAlwaysOnTop(true);
        add.setVisible(true);
    }//GEN-LAST:event_btnAddStaffActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainManagerStaff;
    private javax.swing.JButton btnAddStaff;
    private javax.swing.JButton btnEditStaff;
    private javax.swing.JButton btnEditStaff1;
    private javax.swing.JComboBox<String> combbPosition;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableData;
    private Views.RoundedTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
